preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClass: false
  defaultFsType: ext4
  defaultClassReplicaCount: 2

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 2

  replicaSoftAntiAffinity: true
  storageMinimalAvailablePercentage: 15
  storageOverProvisioningPercentage: 200

  upgradeChecker: false
 # Label your nodes like this to make them available for Longhorn:
 # `kubectl label node pi-002 node.longhorn.io/create-default-disk=true`
 # Then, the following setting will take care of the rest:
  createDefaultDiskLabeledNodes: true

