apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - github.com/fedoteh/oled-agent//k8s/base?ref=main

images:
  - name: fedoteh/oled-agent
    newTag: "v0.1.2"